import {
  faBlog,
  faUsers,
  faUser,
  faDatabase,
  faLaptopCode,
  faAddressCard,
  faHouse,
  faPlus,
  faChartLine,
  faBell,
  faBookOpenReader,
  faArrowUpRightDots,
  faGear,
  faArrowRightFromBracket,
  faChevronLeft,
  faChevronRight,
  faShareNodes,
  faBookmark,
  faArrowTrendUp,
  faEye,
  faHandshake,
  faBold,
  faItalic,
  faUnderline,
  faStrikethrough,
  faAlignLeft,
  faAlignCenter,
  faAlignRight,
  faListUl,
  faListOl,
  faCode,
  faImage,
  faLink,
  faUpload,
  faFloppyDisk,
  faCalendar,
  faTriangleExclamation,
  faCircleCheck,
  faEarthAfrica,
  faComments,
  faRecycle,
  faThumbsUp,
  faTrash,
  faFilePdf,
  faFilePowerpoint,
  faFileWord,
  faXmark,
  faAngleDown,
  faFlag,
  faPenToSquare,
  faGlobe,
  faSun,
  faMoon,
  faPalette,
  faRocket,
  faServer,
  faBrain,
  faMicrochip,
  faBriefcase,
  faDiagramProject,
  faBuilding,
  faGraduationCap,
  faEnvelope,
  faPhone,
  faLocationDot,
} from "@fortawesome/free-solid-svg-icons";
import {
  faSearchengin,
  faFacebook,
  faInstagram,
  faLinkedin,
  faGithub,
  faTwitter,
  faWhatsapp,
} from "@fortawesome/free-brands-svg-icons";

export const ICONS = {
  blog: faBlog,
  users: faUsers,
  database: faDatabase,
  code: faLaptopCode,
  address: faAddressCard,
  searchengin: faSearchengin,
  Home: faHouse,
  Plus: faPlus,
  ChartLine: faChartLine,
  Bell: faBell,
  OpenBook: faBookOpenReader,
  ArrowUpRight: faArrowUpRightDots,
  user: faUser,
  settings: faGear,
  logOut: faArrowRightFromBracket,
  leftArrow: faChevronLeft,
  rightArrow: faChevronRight,
  downArrow: faAngleDown,
  bookMark: faBookmark,
  share: faShareNodes,
  trend: faArrowTrendUp,
  eye: faEye,
  handShake: faHandshake,
  bold: faBold,
  italic: faItalic,
  underline: faUnderline,
  strickThrough: faStrikethrough,
  alignLeft: faAlignLeft,
  alignCenter: faAlignCenter,
  alignRight: faAlignRight,
  ulList: faListUl,
  olList: faListOl,
  code2: faCode,
  img: faImage,
  link: faLink,
  publish: faUpload,
  saveDraft: faFloppyDisk,
  schedule: faCalendar,
  warning: faTriangleExclamation,
  done: faCircleCheck,
  world: faEarthAfrica,
  comment: faComments,
  repost: faRecycle,
  like: faThumbsUp,
  trash: faTrash,
  pdf: faFilePdf,
  powerpoint: faFilePowerpoint,
  word: faFileWord,
  close: faXmark,
  flag: faFlag,
  edit: faPenToSquare,
  globe: faGlobe,
  sun: faSun,
  moon: faMoon,
  facebook: faFacebook,
  instagram: faInstagram,
  linkedIn: faLinkedin,
  github: faGithub,
  twitter: faTwitter,
  whatsapp: faWhatsapp,
  palette: faPalette,
  server: faServer,
  rocket: faRocket,
  brain: faBrain,
  microship: faMicrochip,
  career: faBriefcase,
  project: faDiagramProject,
  underDevelop: faBuilding,
  graduation: faGraduationCap,
  envlope: faEnvelope,
  phone: faPhone,
  location: faLocationDot,
};
